# Generated by Django 5.2.17 on 2026-09-21 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_sinhala', models.CharField(max_length=255, verbose_name='දෙමාපිය / භාරකරුගේ නම')),
                ('primary_phone', models.CharField(db_index=True, max_length=20, verbose_name='ප්\u200dරධාන දුරකථන අංකය')),
                ('whatsapp_phone', models.CharField(blank=True, max_length=20, verbose_name='වට්ස්ඇප් (WhatsApp) අංකය')),
                ('address', models.TextField(verbose_name='ලිපිනය')),
                ('occupation', models.CharField(blank=True, max_length=100, verbose_name='රැකියාව')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_profiles', to='teachers.teacher', verbose_name='දහම් පාසලේ ගුරුභවතෙක් නම් (Linked Teacher)')),
            ],
            options={
                'verbose_name': 'දෙමාපිය / භාරකරු',
                'verbose_name_plural': 'දෙමාපියන් / භාරකරුවන් (Guardians)',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ඇතුළත් වීමේ අංකය (Admission No)')),
                ('full_name_sinhala', models.CharField(max_length=255, verbose_name='සම්පූර්ණ නම (සිංහලෙන්)')),
                ('name_with_initials_sinhala', models.CharField(max_length=255, verbose_name='මුලකුරු සමඟ නම')),
                ('dob', models.DateField(verbose_name='උපන් දිනය')),
                ('gender', models.CharField(choices=[('MALE', 'පිරිමි (Male)'), ('FEMALE', 'ගැහැණු (Female)')], default='MALE', max_length=10, verbose_name='ස්ත්\u200dරී / පුරුෂ භාවය')),
                ('relationship_to_guardian', models.CharField(choices=[('FATHER', 'පියා (Father)'), ('MOTHER', 'මව (Mother)'), ('GUARDIAN', 'භාරකරු (Guardian)'), ('OTHER', 'වෙනත් (Other)')], default='FATHER', max_length=20, verbose_name='භාරකරුගේ ඥාතිත්වය')),
                ('medical_notes', models.TextField(blank=True, verbose_name='සෞඛ්\u200dය ගැටළු / ආසාත්මිකතා (ඇත්නම්)')),
                ('special_notes', models.TextField(blank=True, verbose_name='වෙනත් විශේෂ සටහන්')),
                ('status', models.CharField(choices=[('PENDING', 'අනුමැතිය අපේක්ෂිත (Pending Verification)'), ('APPROVED', 'අනුමත කළ (Active Student)'), ('REJECTED', 'ප්\u200dරතික්ෂේපිත (Rejected)'), ('INACTIVE', 'අක්\u200dරිය (Inactive)')], default='PENDING', max_length=20, verbose_name='ලියාපදිංචි තත්ත්වය')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='තහවුරු කළ දිනය')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ලියාපදිංචි වූ දිනය')),
                ('applied_grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applied_students', to='academics.gradelevel', verbose_name='ඉල්ලුම් කරන ශ්\u200dරේණිය')),
                ('assigned_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.classsection', verbose_name='අනුයුක්ත පන්තිය')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.guardian', verbose_name='දෙමාපිය / භාරකරු')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_students', to=settings.AUTH_USER_MODEL, verbose_name='තහවුරු කළ පරිශීලකයා')),
            ],
            options={
                'verbose_name': 'ශිෂ්\u200dයයා',
                'verbose_name_plural': 'සිසුන් (Students)',
                'ordering': ['applied_grade__order_index', 'admission_number', 'name_with_initials_sinhala'],
            },
        ),
    ]
