# Generated by Django 5.2.17 on 2026-09-21 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'පද්ධති පරිපාලක (System Admin)'), ('PRINCIPAL', 'ප්\u200dරධානාචාර්ය (Principal)'), ('TEACHER', 'ගුරුභවතා (Teacher)')], default='TEACHER', max_length=20, verbose_name='භූමිකාව (Role)')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='දුරකථන අංකය')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'පරිශීලක පැතිකඩ',
                'verbose_name_plural': 'පරිශීලක පැතිකඩවල්',
            },
        ),
    ]
