# Generated by Django 5.2.17 on 2026-09-21 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('VEN', 'පූජ්\u200dය (Venerable)'), ('MR', 'ගුරු මයා (Mr.)'), ('MRS', 'ගුරු මිය (Mrs.)'), ('MISS', 'මෙනවිය (Miss)')], default='MR', max_length=10, verbose_name='ගෞරව නාමය')),
                ('full_name_sinhala', models.CharField(max_length=255, verbose_name='සම්පූර්ණ නම (සිංහලෙන්)')),
                ('name_with_initials', models.CharField(max_length=255, verbose_name='මුලකුරු සමඟ නම')),
                ('phone', models.CharField(max_length=20, verbose_name='දුරකථන අංකය')),
                ('whatsapp_phone', models.CharField(blank=True, max_length=20, verbose_name='වට්ස්ඇප් (WhatsApp) අංකය')),
                ('address', models.TextField(blank=True, verbose_name='ලිපිනය')),
                ('qualifications', models.TextField(blank=True, verbose_name='සුදුසුකම් (උදා: ධර්මාචාර්ය, උපාධිධාරී)')),
                ('date_joined', models.DateField(blank=True, null=True, verbose_name='සේවයට බැඳුණු දිනය')),
                ('is_active', models.BooleanField(default=True, verbose_name='ක්\u200dරියාකාරී ගුරුභවතෙක්ද?')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='පරිශීලක ගිණුම')),
            ],
            options={
                'verbose_name': 'ගුරුභවතා',
                'verbose_name_plural': 'ගුරුභවතුන් (Teachers)',
                'ordering': ['full_name_sinhala'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='බුද්ධ ධර්මය', max_length=100, verbose_name='විෂයය (Subject)')),
                ('is_class_teacher', models.BooleanField(default=False, verbose_name='ප්\u200dරධාන පන්තිභාර ගුරුභවතාද?')),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_allocations', to='academics.classsection', verbose_name='පන්තිය')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='teachers.teacher', verbose_name='ගුරුභවතා')),
            ],
            options={
                'verbose_name': 'ගුරු අනුයුක්තය',
                'verbose_name_plural': 'ගුරු අනුයුක්ත කිරීම් (Teacher Allocations)',
                'unique_together': {('teacher', 'class_section', 'subject')},
            },
        ),
    ]
