# Generated by Django 5.2.17 on 2026-09-21 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True, verbose_name='අධ්\u200dයයන වර්ෂය')),
                ('is_current', models.BooleanField(default=False, verbose_name='වත්මන් වර්ෂයද?')),
            ],
            options={
                'verbose_name': 'අධ්\u200dයයන වර්ෂය',
                'verbose_name_plural': 'අධ්\u200dයයන වර්ෂ (Academic Years)',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ශාලාව / කාමරයේ නම')),
                ('capacity', models.PositiveIntegerField(default=40, verbose_name='ධාරිතාව')),
            ],
            options={
                'verbose_name': 'පන්ති කාමරය / ශාලාව',
                'verbose_name_plural': 'පන්ති කාමර / ශාලා',
            },
        ),
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ශ්\u200dරේණියේ නම (Sinhala)')),
                ('english_name', models.CharField(blank=True, max_length=100, verbose_name='නම (English)')),
                ('order_index', models.PositiveIntegerField(default=1, verbose_name='අනුපිළිවෙල අංකය')),
                ('description', models.TextField(blank=True, verbose_name='විස්තරය')),
            ],
            options={
                'verbose_name': 'ශ්\u200dරේණිය',
                'verbose_name_plural': 'ශ්\u200dරේණි (Grades)',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='ClassSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(default='ප්\u200dරධාන', max_length=50, verbose_name='කාණ්ඩය / පන්තියේ නම')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.academicyear', verbose_name='අධ්\u200dයයන වර්ෂය')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.classroom', verbose_name='පන්ති කාමරය')),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.gradelevel', verbose_name='ශ්\u200dරේණිය')),
            ],
            options={
                'verbose_name': 'පන්තිය',
                'verbose_name_plural': 'පන්ති (Class Sections)',
                'ordering': ['grade_level__order_index', 'section_name'],
                'unique_together': {('grade_level', 'academic_year', 'section_name')},
            },
        ),
    ]
