# Generated by Django 5.2.17 on 2026-09-21 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SundaySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='දිනය (Sunday Date)')),
                ('term', models.PositiveSmallIntegerField(choices=[(1, '1 වන වාරය (Term 1)'), (2, '2 වන වාරය (Term 2)'), (3, '3 වන වාරය (Term 3)')], default=1, verbose_name='වාරය')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='විශේෂ සටහන (උදා: පෝය දින වැඩසටහන)')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sunday_sessions', to='academics.academicyear', verbose_name='අධ්\u200dයයන වර්ෂය')),
            ],
            options={
                'verbose_name': 'දහම් පාසල් දිනය',
                'verbose_name_plural': 'දහම් පාසල් දින (Sunday Sessions)',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'පැමිණි (Present)'), ('ABSENT', 'නොපැමිණි (Absent)'), ('EXCUSED', 'නිවාඩු (Excused)'), ('LATE', 'ප්\u200dරමාද (Late)')], default='PRESENT', max_length=15, verbose_name='පැමිණීමේ තත්ත්වය')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='යාවත්කාලීන වූ දිනය')),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academics.classsection', verbose_name='පන්තිය')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='සටහන් කළ පරිශීලකයා')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student', verbose_name='ශිෂ්\u200dයයා')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.sundaysession', verbose_name='දිනය')),
            ],
            options={
                'verbose_name': 'පැමිණීමේ සටහන',
                'verbose_name_plural': 'පැමිණීමේ සටහන් (Attendance Records)',
                'unique_together': {('session', 'student')},
            },
        ),
    ]
